amino_acid_codons_rna = {
    'Alanine': ['GCU', 'GCC', 'GCA', 'GCG'],
    'Arginine': ['CGU', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'],
    'Asparagine': ['AAU', 'AAC'],
    'Aspartic Acid': ['GAU', 'GAC'],
    'Cysteine': ['UGU', 'UGC'],
    'Glutamine': ['CAA', 'CAG'],
    'Glutamic Acid': ['GAA', 'GAG'],
    'Glycine': ['GGU', 'GGC', 'GGA', 'GGG'],
    'Histidine': ['CAU', 'CAC'],
    'Isoleucine': ['AUU', 'AUC', 'AUA'],
    'Leucine': ['UUA', 'UUG', 'CUU', 'CUC', 'CUA', 'CUG'],
    'Lysine': ['AAA', 'AAG'],
    'Methionine': ['AUG'],
    'Phenylalanine': ['UUU', 'UUC'],
    'Proline': ['CCU', 'CCC', 'CCA', 'CCG'],
    'Serine': ['UCU', 'UCC', 'UCA', 'UCG', 'AGU', 'AGC'],
    'Threonine': ['ACU', 'ACC', 'ACA', 'ACG'],
    'Tryptophan': ['UGG'],
    'Tyrosine': ['UAU', 'UAC'],
    'Valine': ['GUU', 'GUC', 'GUA', 'GUG'],
    'Stop Codon': ['UAA', 'UAG', 'UGA']
}

amino_acid_codons = {
    'Alanine': ['GCT', 'GCC', 'GCA', 'GCG'],
    'Arginine': ['CGT', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'],
    'Asparagine': ['AAT', 'AAC'],
    'Aspartic Acid': ['GAT', 'GAC'],
    'Cysteine': ['TGT', 'TGC'],
    'Glutamine': ['CAA', 'CAG'],
    'Glutamic Acid': ['GAA', 'GAG'],
    'Glycine': ['GGT', 'GGC', 'GGA', 'GGG'],
    'Histidine': ['CAT', 'CAC'],
    'Isoleucine': ['ATT', 'ATC', 'ATA'],
    'Leucine': ['TTA', 'TTG', 'CTT', 'CTC', 'CTA', 'CTG'],
    'Lysine': ['AAA', 'AAG'],
    'Methionine': ['ATG'],
    'Phenylalanine': ['TTT', 'TTC'],
    'Proline': ['CCT', 'CCC', 'CCA', 'CCG'],
    'Serine': ['TCT', 'TCC', 'TCA', 'TCG', 'AGT', 'AGC'],
    'Threonine': ['ACT', 'ACC', 'ACA', 'ACG'],
    'Tryptophan': ['TGG'],
    'Tyrosine': ['TAT', 'TAC'],
    'Valine': ['GTT', 'GTC', 'GTA', 'GTG'],
    'Stop Codon': ['TAA', 'TAG', 'TGA']
}

rna_codon_amino_acids = {
    'GCU': 'Alanine', 'GCC': 'Alanine', 'GCA': 'Alanine', 'GCG': 'Alanine',
    'CGU': 'Arginine', 'CGC': 'Arginine', 'CGA': 'Arginine', 'CGG': 'Arginine', 'AGA': 'Arginine', 'AGG': 'Arginine',
    'AAU': 'Asparagine', 'AAC': 'Asparagine',
    'GAU': 'Aspartic_Acid', 'GAC': 'Aspartic_Acid',
    'UGU': 'Cysteine', 'UGC': 'Cysteine',
    'CAA': 'Glutamine', 'CAG': 'Glutamine',
    'GAA': 'Glutamic_Acid', 'GAG': 'Glutamic_Acid',
    'GGU': 'Glycine', 'GGC': 'Glycine', 'GGA': 'Glycine', 'GGG': 'Glycine',
    'CAU': 'Histidine', 'CAC': 'Histidine',
    'AUU': 'Isoleucine', 'AUC': 'Isoleucine', 'AUA': 'Isoleucine',
    'UUA': 'Leucine', 'UUG': 'Leucine', 'CUU': 'Leucine', 'CUC': 'Leucine', 'CUA': 'Leucine', 'CUG': 'Leucine',
    'AAA': 'Lysine', 'AAG': 'Lysine',
    'AUG': 'Methionine',
    'UUU': 'Phenylalanine', 'UUC': 'Phenylalanine',
    'CCU': 'Proline', 'CCC': 'Proline', 'CCA': 'Proline', 'CCG': 'Proline',
    'UCU': 'Serine', 'UCC': 'Serine', 'UCA': 'Serine', 'UCG': 'Serine', 'AGU': 'Serine', 'AGC': 'Serine',
    'ACU': 'Threonine', 'ACC': 'Threonine', 'ACA': 'Threonine', 'ACG': 'Threonine',
    'UGG': 'Tryptophan',
    'UAU': 'Tyrosine', 'UAC': 'Tyrosine',
    'GUU': 'Valine', 'GUC': 'Valine', 'GUA': 'Valine', 'GUG': 'Valine',
    'UAA': 'Stop', 'UAG': 'Stop', 'UGA': 'Stop'
}
