"""Added otp colunm to user

Revision ID: 33d753e6e0b2
Revises: 064569d4ad4e
Create Date: 2024-08-11 02:36:44.306100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d753e6e0b2'
down_revision: Union[str, None] = '064569d4ad4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('OTP', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'OTP')
    # ### end Alembic commands ###
